/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_morse_zip_ZipUtils */

#ifndef _Included_com_morse_zip_ZipUtils
#define _Included_com_morse_zip_ZipUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_morse_zip_ZipUtils
 * Method:    excuteCommand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_morse_zip_ZipUtils_excuteCommand
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
